### ISSUE TITLE
any possible to load css  or js offline in report

### ISSUE THREAD

**Issue by yuxh** [scoverage/scoverage-maven-plugin#78] opened 2020-01-07 08:22 UTC
Every time it takes some time to download css and js in report(my network is not very desirable),  any possible way to switch to offline mode?

**Comment by jozic** [comment] 2023-12-28 21:27
Hey @yuxh 
I believe that was addressed in the main component by https://github.com/scoverage/scalac-scoverage-plugin/pull/236. 
Please try one of the latest versions to check if the issue is gone.
Please reopen with more details if you still have issues.

**Closed by jozic** 2023-12-28 21:27 UTC
