### ISSUE TITLE
How to resolve scoverage-maven-plugin:1.1.0-SNAPSHOT Skipping SCoverage report generation

### ISSUE THREAD

**Issue by abdheshkumar** [scoverage/scoverage-maven-plugin#21] opened 2015-05-21 08:14 UTC
Hi 
I am trying to integrate scoverage with maven  but am getting SCoverage report generation  info in logger

These are the steps that i followed :
1. Integrate configuration in xml file
pom.xml
```html
<plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>${scoverage.plugin.version}</version>
                <executions>
                    <execution>
                        <id>coverage</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <excludedFiles>.*Object</excludedFiles>
                </configuration>
            </plugin>
```
2. run  mvn scoverage:report

I don't know this configuration is right or not. Please guide me how can i make this working.

Thanks

**Comment by gslowikowski** [comment] 2015-05-21 08:20
Hi

Add
```xml
    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
```
to your `pom.xml`.

**Comment by abdheshkumar** [comment] 2015-05-21 08:24
I added that you suggested but i am still getting same issue:

[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.0-SNAPSHOT:report (default-cli) < [scoverage]test @ harvester <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.0-SNAPSHOT:report (default-cli) @ harvester ---
[INFO] Skipping SCoverage report generation
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 min
[INFO] Finished at: 2015-05-21T13:53:41+05:30
[INFO] Final Memory: 36M/95M

**Comment by abdheshkumar** [comment] 2015-05-21 08:28
Here is the complete pom configuration:
```html

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <properties>
        <scoverage.plugin.version>1.1.0-SNAPSHOT</scoverage.plugin.version>
    </properties>
    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
    <build>
        <plugins>
            <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>${scoverage.plugin.version}</version>
                <executions>
                    <execution>
                        <id>coverage</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <excludedFiles>.*Object</excludedFiles>
                </configuration>
            </plugin>

        </plugins>
    </build>
</project>
``

**Comment by gslowikowski** [comment] 2015-05-21 08:46
Does it work with version `1.0.4`?

**Comment by abdheshkumar** [comment] 2015-05-21 08:57
No it doesn't work with 1.0.4 too?
Maybe i configured in wrong way. The configuration that i posted is correct?

**Comment by gslowikowski** [comment] 2015-05-21 09:54
It should work with `1.0.4`.
Does not work with `1.1.0-SNAPSHOT`, I found a bug introduced recently. Anyway, it does not print `Skipping SCoverage report generation` for me. Can you attach (or send me directly, if you cannot publish it) Maven execution log with debug info ( `-X` option)?

**Comment by abdheshkumar** [comment] 2015-05-21 10:35
``html
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <properties>
        <scoverage.plugin.version>1.0.4</scoverage.plugin.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.scoverage</groupId>
                    <artifactId>scoverage-maven-plugin</artifactId>
                    <version>1.0.4</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            
	<plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>${scoverage.plugin.version}</version>
                <configuration>
                    <scalaVersion>2.10.2</scalaVersion>
                </configuration>
            </plugin>
            
        </plugins>
    </build>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>1.0.4</version>
            </plugin>
        </plugins>
    </reporting>
</project>

```


Above is project pom.xml file configuration, please check that all is right configuration?
Now i am not getting Skipping SCoverage report generation error when i run mvn scoverage:report but it throwing exception [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.3:compile (scala-compile-first) on project scala-scoverage-demo: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.1.3:compile failed. NullPointerException -> [Help 1]  

When i run mvn compile it compile all files successfully. I don't know what the happening...:-(

**Comment by gslowikowski** [comment] 2015-05-21 10:40
I need execution log.

**Comment by gslowikowski** [comment] 2015-06-08 06:23
Hi
`1.1.0` version was released yesterday. Try it, please.
Without sample project or your execution log I cannot reproduce the issue and will close this issue.

**Comment by abdheshkumar** [comment] 2015-06-08 06:39
Hi @gslowikowski 
I am getting same issue like this https://github.com/scoverage/scalac-scoverage-plugin/issues/93
and i am running on scala 2.10.

**Comment by gslowikowski** [comment] 2015-06-08 07:08
So something has changed, you had no exception before. Anyway this is not a Maven plugin issue.  I still cannot help you without sample project. Tried to build your project https://github.com/abdheshkumar/sbt-poc-coverage, but it works for me.

**Comment by abdheshkumar** [comment] 2015-06-08 07:38
Yes @gslowikowski  it's working fine with Scala 2.11+ but its not working 2.10 at least for me.

**Comment by gslowikowski** [comment] 2015-06-08 09:55
Ok, I'm closing, this is not Maven plugin issue.

**Closed by gslowikowski** 2015-06-08 09:55 UTC

**Comment by ryan-williams** [comment] 2016-08-27 19:32
Just a quick drive-by to note that I was just seeing the 

```
[INFO] Skipping SCoverage report generation
```

message and eventually realized it was because my POM had `<packaging>pom</packaging>` instead of `<packaging>jar</packaging>` due to a copy/paste error on my end.

**Comment by abdheshkumar** [comment] 2016-08-27 19:51
So now it would work with Scala 2.10?

**Comment by abdheshkumar** [comment] 2016-08-27 20:27
Still same issue:

[INFO] >>> scoverage-maven-plugin:1.1.1:report (default-cli) > [scoverage]test @ root >>>
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (default-cli) @ root ---
[INFO] Skipping SCoverage execution for project with packaging type 'pom'

[INFO] >>> scoverage-maven-plugin:1.1.1:report (default-cli) > [scoverage]test @ common >>>
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (default-cli) @ common ---
[WARNING] Skipping SCoverage execution - unsupported Scala version "2.10"

[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.1:report (default-cli) < [scoverage]test @ common <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:report (default-cli) @ common ---
[INFO] Skipping SCoverage report generation
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building workflow 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> scoverage-maven-plugin:1.1.1:report (default-cli) > [scoverage]test @ workflow >>>
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.1:pre-compile (default-cli) @ workflow ---
[WARNING] Skipping SCoverage execution - unsupported Scala version "2.10"
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ workflow ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.

**Comment by gslowikowski** [comment] 2016-08-28 09:19
@abdheshkumar 
From your logs:
```
[WARNING] Skipping SCoverage execution - unsupported Scala version "2.10"
```

**Comment by kunal642** [comment] 2016-11-16 09:41
@abdheshkumar were you able to resolve this issue?
