### ISSUE TITLE
[Concurrency] scoverage-maven-plugin is not thread safe

### ISSUE THREAD

**Issue by harrysingh** [scoverage/scoverage-maven-plugin#92] opened 2021-04-09 06:36 UTC
When running build for multi module project, maven complains for scoverage-maven-plugin not being thread safe
```
 [WARNING] The following plugins are not marked @threadSafe in <module name>:
 [WARNING] org.scoverage:scoverage-maven-plugin:1.4.1
 [WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
 [WARNING] *****************************************************************

```

Also, when project is run with parallelism, aggregation either fails or is incorrect.

P.S. When running with no parallelism, module data is aggregated correctly.

**Comment by RPCMoritz** [comment] 2023-02-13 15:13
Duplicates #83 ?

**Comment by jozic** [comment] 2023-10-27 01:51
closing as duplicate of #83
@harrysingh please comment if you believe it's not a duplicate

**Closed by jozic** 2023-10-27 01:51 UTC
