### ISSUE TITLE
scoverage and pax exam

### ISSUE THREAD

**Issue by efisant** [scoverage/scoverage-maven-plugin#5] opened 2014-05-27 11:47 UTC
Hello,
your project seems very promising, congrats! However, it seems to me that not all types of tests are handled. How about the integration tests in pax exam env, how could these be supported by scoverage?

Thank you

**Comment by gslowikowski** [comment] 2015-01-09 08:34
Can we close this issue?

**Comment by efisant** [comment] 2015-01-09 08:42
since not supported, yes you can close it. thanks!

**Comment by gslowikowski** [comment] 2015-01-09 10:42
I tried to learn Pax Exam, but sample project I found (https://github.com/ops4j/org.ops4j.pax.exam2/tree/v3.0.x/itest/osgi/src/it/regression-maven-plugin) does not work for me, test fails with ``java.lang.ClassNotFoundException: org.osgi.framework.launch.FrameworkFactory``. Can you attach something to test?

**Comment by gslowikowski** [comment] 2015-01-09 10:52
I mean Maven project, not SBT.

**Comment by gslowikowski** [comment] 2015-01-09 12:46
It works, but there are no Scala files. SCoverage does not work with Java files.

**Comment by efisant** [comment] 2015-01-09 13:46
Really sorry, cannot help you more.
What about converting java to scala for a very simple project like following?https://github.com/ops4j/org.ops4j.pax.exam2/tree/master/samples/exam-itest-sample-karaf

**Comment by gslowikowski** [comment] 2015-01-21 08:49
Right now scoverage plugins are not ready for this use case. I will try to do something with it in the future. Calculating coverage of packaged artifacts (not only OSGI bundles) in separate modules/projects is very interesting feature to implement.

**Comment by gslowikowski** [comment] 2015-06-08 09:59
This is not possible due to `scalac-scoverage-plugin` limitations (there are more related issues around). I'm closing this issue because I cannot do anything.

**Closed by gslowikowski** 2015-06-08 09:59 UTC

**Comment by gslowikowski** [comment] 2016-02-24 20:11
@efisant, I would like to return to this issue.

Since version `1.1.0` we have [integration-check](http://scoverage.github.io/scoverage-maven-plugin/1.1.1/integration-check-mojo.html) and [integration-report](http://scoverage.github.io/scoverage-maven-plugin/1.1.1/integration-report-mojo.html) goals.

In forked `scoverage` lifecycle, in `package` phase, instrumented `jar` (or any other packaging) file is created. To avoid overriding the original one, `scoverage-` prefix is prepended to file name.
Maybe this instrumented file could be used during Pax Exam tests.

I've started [simple test project](https://github.com/gslowikowski/pax-exam-it-sample), but tests fail (without Scoverage). Maybe you will help me.
Pax Exam expects artifact jar, so I moved testing from `test` phase (unit testing, using `.class` files in `target/classes`) to `integration-test` phase (integration testing, using `jar` file).
This did not help. Installing `pax-exam-sample8-ds` artifact first did not help too.

To run integration tests execute `mvn verify`.

Can you help me with this?
